---
# tasks file for role-mailcatcher
- name: Install required software
  apt: pkg={{ item }} state=present
  with_items:
      - build-essential
      - sqlite3
      - libsqlite3-dev
      - ruby-dev
      - ruby
  sudo: yes

- name: Check for mailcatcher
  command: which mailcatcher
  register: mailcatcher_status

- name: Install Mailcatcher
  command: gem install mailcatcher
  sudo: yes
  when: "'bin/mailcatcher' not in mailcatcher_status.stdout"

- name: Kill previous mailcatcher
  command: pkill -9 mailcatcher
  sudo: yes

- name: Start mailcatcher
  command: mailcatcher --ip={{ mailcatcher_ip }} --smtp-ip={{ mailcatcher_smtp_ip }} --smtp-port={{ mailcatcher_smtp_port }} --http-ip={{ mailcatcher_http_ip }} --http-port={{ mailcatcher_http_port }}
  sudo: yes
