---
# tasks file for role-mailcatcher
- name: Install required software
  apt: pkg={{ item }} state=present
  with_items:
      - build-essential
      - sqlite3
      - libsqlite3-dev
      - ruby-dev
      - ruby
  sudo: yes

- name: Check for mailcatcher
  command: which mailcatcher
  register: mailcatcher_status

- name: Install Mailcatcher
  command: gem install mailcatcher
  sudo: yes
  when: "'bin/mailcatcher' not in mailcatcher_status.stdout"

- name: Create startup script for mailcatcher
  template: src=mailcatcher.j2 dest=/etc/init.d/mailcatcher mode=0755
  sudo: yes

- name: Start mailcatcher with the script
  service: name=mailcatcher state=started
  sudo: yes
